### Create a new user
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword",
  "role": "admin"
}

### Retrieve all users
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

### Retrieve a specific user by ID
GET http://127.0.0.1:8000/api/users/2/
Content-Type: application/json

### Update a user
PUT http://127.0.0.1:8000/api/users/2/
Content-Type: application/json

{
  "username": "updateduser",
  "password": "updatedpassword",
  "role": "manager"
}

### Delete a user
DELETE http://127.0.0.1:8000/api/users/2/
Content-Type: application/json

### Create a new customer
POST http://127.0.0.1:8000/api/customers/
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "phone_number": "1234567890",
  "address": "123 Main St"
}

### Retrieve all customers
GET http://127.0.0.1:8000/api/customers/
Content-Type: application/json

### Retrieve a specific customer by ID
GET http://127.0.0.1:8000/api/customers/2/
Content-Type: application/json

### Update a customer
PUT http://127.0.0.1:8000/api/customers/2/
Content-Type: application/json

{
  "first_name": "Jane",
  "last_name": "Smith",
  "email": "jane.smith@example.com",
  "phone_number": "0987654321",
  "address": "456 Main St"
}

### Delete a customer
DELETE http://127.0.0.1:8000/api/customers/2/
Content-Type: application/json

### Create a new category
POST http://127.0.0.1:8000/api/categories/
Content-Type: application/json

{
  "name": "Beer"
}

### Retrieve all categories
GET http://127.0.0.1:8000/api/categories/
Content-Type: application/json

### Retrieve a specific category by ID
GET http://127.0.0.1:8000/api/categories/3/
Content-Type: application/json

### Update a category
PUT http://127.0.0.1:8000/api/categories/3/
Content-Type: application/json

{
  "name": "Soft Drinks"
}

### Delete a category
DELETE http://127.0.0.1:8000/api/categories/3/
Content-Type: application/json

### Create a new product
POST http://127.0.0.1:8000/api/products/
Content-Type: application/json

{
  "name": "Dhiziri",
  "description": "Black Label",
  "price": 0.50,
  "category": 4,
  "quantity_in_stock": 50,
  "unit": "piece"
}

### Retrieve all products
GET http://127.0.0.1:8000/api/products/
Content-Type: application/json

### Retrieve a specific product by ID
GET http://127.0.0.1:8000/api/products/2/
Content-Type: application/json

### Update a product
PUT http://127.0.0.1:8000/api/products/2/
Content-Type: application/json

{
  "name": "Pepsi Drink",
  "description": "Pepsi",
  "price": 0.50,
  "category": 4,
  "quantity_in_stock": 30,
  "unit": "piece"
}

### Delete a product
DELETE http://127.0.0.1:8000/api/products/1/
Content-Type: application/json



### Create a Supplier
POST http://127.0.0.1:8000/api/suppliers/
Content-Type: application/json

{
    "name": "Supplier A",
    "contact_person": "John Doe",
    "phone_number": "1234567890",
    "email": "supplier@example.com",
    "address": "123 Supplier St.",
    "remarks": "First supplier."
}

### Get All Suppliers
GET http://127.0.0.1:8000/api/suppliers/

### Get Supplier by ID
GET http://127.0.0.1:8000/api/suppliers/1/

### Update a Supplier
PUT http://127.0.0.1:8000/api/suppliers/1/
Content-Type: application/json

{
    "name": "Supplier A",
    "contact_person": "Jane Doe",
    "phone_number": "0987654321",
    "email": "supplier_new@example.com",
    "address": "123 Supplier St.",
    "remarks": "Updated supplier."
}

### Delete a Supplier
DELETE http://127.0.0.1:8000/api/suppliers/1/

### Create a Purchase Order
POST http://127.0.0.1:8000/api/purchase_orders/
Content-Type: application/json

{
    "supplier": 2
}

### Get All Purchase Orders
GET http://127.0.0.1:8000/api/purchase_orders/

### Get Purchase Order by ID
GET http://127.0.0.1:8000/api/purchase_orders/1/

### Update a Purchase Order
PUT http://127.0.0.1:8000/api/purchase_orders/1/
Content-Type: application/json

{
    "supplier": 1
}

### Delete a Purchase Order
DELETE http://127.0.0.1:8000/api/purchase_orders/1/

### Create a Purchase Order Item
POST http://127.0.0.1:8000/api/purchase_order_items/
Content-Type: application/json

{
    "purchase_order": 1,
    "product_id": 1,
    "quantity": 10,
    "price": 50.00,
    "total_amount": 500.00,
    "status": "pending"
}

### Get All Purchase Order Items
GET http://127.0.0.1:8000/api/purchase_order_items/

### Get Purchase Order Item by ID
GET http://127.0.0.1:8000/api/purchase_order_items/1/

### Update a Purchase Order Item
PUT http://127.0.0.1:8000/api/purchase_order_items/1/
Content-Type: application/json

{
    "purchase_order": 1,
    "product_id": 1,
    "quantity": 15,
    "price": 50.00,
    "total_amount": 750.00,
    "status": "completed"
}

### Delete a Purchase Order Item
DELETE http://127.0.0.1:8000/api/purchase_order_items/
